### PR TITLE
tps crash request to include crashed cell id

### PR DESCRIPTION
**Pull request by nimakaviani**
[#155871993]

Signed-off-by: Edwin Xie <exie@pivotal.io>

### CODE REVIEW

**Comment by ewrenn8** [comment]
Hey @nimakaviani ,

We ran all the unit tests on your code and had a failure. We've included the error below. Can you look into this issue?

Thanks!
Eli && @lisamcho 
```
[1529605230] CcClient Suite - 3 specs - 4 nodes ••
------------------------------
2018/06/21 18:20:44 http: multiple response.WriteHeader calls
[BeforeEach] CC Client
  /go/capi-release/src/code.cloudfoundry.org/tps/cc_client/cc_client_test.go:27
[BeforeEach] Successfully calling the Cloud Controller
  /go/capi-release/src/code.cloudfoundry.org/tps/cc_client/cc_client_test.go:50
[It] sends the request payload to the CC without modification
  /go/capi-release/src/code.cloudfoundry.org/tps/cc_client/cc_client_test.go:66
{"timestamp":"1529605244.702968359","source":"fakelogger","message":"fakelogger.cc-client.delivering-app-crashed-response","log_level":0,"data":{"app_crashed":{"instance":"","index":1,"reason":"","crash_count":0,"crash_timestamp":0},"session":"1"}}
{"timestamp":"1529605244.716035843","source":"fakelogger","message":"fakelogger.cc-client.delivered-app-crashed-response","log_level":0,"data":{"session":"1"}}
[AfterEach] CC Client
  /go/capi-release/src/code.cloudfoundry.org/tps/cc_client/cc_client_test.go:41


• Failure [0.043 seconds]
CC Client Successfully calling the Cloud Controller [It] sends the request payload to the CC without modification
/go/capi-release/src/code.cloudfoundry.org/tps/cc_client/cc_client_test.go:66

  Expected
      <[]uint8 | len:73, cap:512>: {"instance":"","index":1,"reason":"","crash_count":0,"crash_timestamp":0}
  to equal
      <[]uint8 | len:86, cap:96>: {"instance":"","index":1,"cell_id":"","reason":"","crash_count":0,"crash_timestamp":0}

  /go/capi-release/src/code.cloudfoundry.org/tps/cc_client/cc_client_test.go:60

  Full Stack Trace
  	/go/capi-release/src/github.com/onsi/gomega/internal/assertion/assertion.go:69 +0x25b
  github.com/onsi/gomega/internal/assertion.(*Assertion).To(0xc4202fa380, 0xc70f60, 0xc4202fc0a0, 0x0, 0x0, 0x0, 0xc4202fa380)
  	/go/capi-release/src/github.com/onsi/gomega/internal/assertion/assertion.go:35 +0xd0
  code.cloudfoundry.org/tps/cc_client_test.glob..func1.3.1.1(0xc712a0, 0xc420312000, 0xc420302000)
  	/go/capi-release/src/code.cloudfoundry.org/tps/cc_client/cc_client_test.go:60 +0x32b
  github.com/onsi/gomega/ghttp.CombineHandlers.func1(0xc712a0, 0xc420312000, 0xc420302000)
  	/go/capi-release/src/github.com/onsi/gomega/ghttp/handlers.go:22 +0xa4
  github.com/onsi/gomega/ghttp.(*Server).ServeHTTP(0xc420270080, 0xc712a0, 0xc420312000, 0xc420302000)
  	/go/capi-release/src/github.com/onsi/gomega/ghttp/test_server.go:258 +0x42b
  net/http.serverHandler.ServeHTTP(0xc420254410, 0xc712a0, 0xc420312000, 0xc420302000)
  	/usr/local/go/src/net/http/server.go:2694 +0xba
  net/http.(*conn).serve(0xc4202f4000, 0xc71960, 0xc4202fa000)
  	/usr/local/go/src/net/http/server.go:1830 +0x7dd
  created by net/http.(*Server).Serve
  	/usr/local/go/src/net/http/server.go:2795 +0x365

------------------------------


Summarizing 1 Failure:

[Fail] CC Client Successfully calling the Cloud Controller [It] sends the request payload to the CC without modification
/go/capi-release/src/code.cloudfoundry.org/tps/cc_client/cc_client_test.go:60

Ran 3 of 3 Specs in 0.086 seconds
FAIL! -- 2 Passed | 1 Failed | 0 Pending | 0 Skipped
[1529605230] TPS-Listener Suite - 9 specs - 4 nodes ••••••••• SUCCESS! 7.323271602s
Failed to compile tps-watcher:
```

**Comment by nimakaviani** [comment]
sorry about that. We forgot to make the PR to runtimeschema. It is there now and needs to be merged before merging this one.

https://github.com/cloudfoundry/runtimeschema/pull/14

**Comment by nimakaviani** [comment]
We merged [this PR](https://github.com/cloudfoundry/runtimeschema/pull/14) to runtimeschema so you should be good pulling from `master` and running the units.

**Comment by nimakaviani** [comment]
Also following [this slack conversation](https://cloudfoundry.slack.com/archives/C02FM2BPE/p1529693384000740), the `runtimeschema` repo is pretty useless now that metrics are removed. You may want to inline `cc_messages` into `cc_uploader` and `tps` so that we can remove the repo.

In the meantime, please make sure you bump `runtimeschema` in `capi-release`. thanks!

**Comment by goonzoid** [comment]
Sounds good. Thanks!

We have https://www.pivotaltracker.com/story/show/158134969 to get rid of `runtimeschema`, so we'll get to that sooner or later 🌻 🍰 🎈

**Pull request merged**
